apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-proxy
  namespace: redis
  labels:
    app: redis-sentinel-proxy
spec:
  type: NodePort
  ports:
  - port: 9999
    name: redis-sentinel-proxy
  selector:
    app: redis-sentinel-proxy