apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy
    spec:
      containers:
      - name: redis-sentinel-proxy
        image: anubhavmishra/redis-sentinel-proxy:latest
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - "-master"
          - "primary"
          - "-sentinel"
          - "redis-sentinel.$(NAMESPACE):26379"
        ports:
        - containerPort: 9999